defaults:
  - base_model_config
  - resnet50
projection_size: 128
ssl_method: BYOL

dataset: mimic-cxr-img_ap-pa_find-impr_03
batch_size: 64
learning_rate: 3e-5
weight_decay: 1e-4

warmup_epochs: 1
max_epochs: 100