defaults:
  - base_model_config
  - resnet50
classifier_task: 'chexpert_binary'

dataset: mimic-cxr-img_ap-pa_find-impr_03
lr_reduce_patience: 3
lr_reduce_factor: 0.5
early_stop_patience: 10
batch_size: 64
learning_rate: 1e-4
weight_decay: 1e-6
max_epochs: 100
