defaults:
  - base_model_config
  - resnet50
projection_size: 512
ssl_method: PixelPro

dataset: mimic-cxr-img_ap-pa_find-impr_03
batch_size: 64
learning_rate: 1e-3
weight_decay: 1e-5

max_epochs: 100