defaults:
  - segmentation_eval

dataset: covid_rural
eval_name: 'covid_unet_finetune'
task: 'covid_rural'
data_augmentation: false
loss_fn: dice
segmentation_head: unet
freeze_encoder: false
frozen_warmup_steps: 20
warmup_lr: 1e-3

batch_size: 8
learning_rate: 1e-4
weight_decay: 1e-6
lr_reduce_patience: 3
lr_reduce_factor: 0.5

max_epochs: 100
