defaults:
  - segmentation_eval

dataset: covid_rural
eval_name: 'covid_lin'
task: 'covid_rural'
data_augmentation: false
loss_fn: dice
segmentation_head: linear
freeze_encoder: true

batch_size: 8
learning_rate: 3e-2
weight_decay: 1e-6
lr_reduce_patience: 3
lr_reduce_factor: 0.5

max_epochs: 100
