defaults:
  - logger:
      - wandb
  - callback:
      - upload_config

name: <unnamed>

seed: 12345
trainer:
  precision: 16
  amp_level: 'O1'

gpus: [0]
num_dataloader_workers: 10

debug: False
print_config: True

work_dir: ${hydra:runtime.cwd}

hydra:
  output_subdir: hydra
  run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
